FORMAT: 1A
HOST: https://tipsymix.com

# TipsyMix

TipsyMix is a database linking cocktails, ingredients, brands, and countries together into an intuitively queriable model.

## Search Query [/api/search{?category,query,filter,count,page,pagesize}]

+ Parameters
    + category (optional) - Type of model to search for (empty = intelligent search)
    + query (optional) - Search query to run
    + filter (optional) - How to filter the results
    + count (optional) - How many results to create
    + page (optional) - What page of the results to return
    + pagesize (optional) - Number of results per page
    
### Query [GET]

+ Response 200 (application/json)

        {
            "category": "cocktails",
            "query": "raspberry",
            "filter": "",
            "totalCount": 90,
            "totalPages": 30,
            "count": 3
            "page": 2
            "results": [
                {
                    "id": 2349542,
                    "stdname": "raspberry-margarita",
                    "label": "Raspberry Margarita",
                    "image": "internal/2349542.jpeg",
                    "url": "tipsymix.com/api/cocktails/raspberry-margarita",
                    "color": 0xA81503
                }, {
                    "id": 2349299,
                    "stdname": "raspberry-mojito",
                    "label": "Raspberry Mojito",
                    "image": "internal/2349299.jpeg",
                    "url": "tipsymix.com/api/cocktails/raspberry-mojito",
                    "color": 0xDA3A13
                }, {
                    "id": 5693234,
                    "stdname": "raspberry-collins",
                    "label": "Raspberry Collins",
                    "image": "internal/5693234.jpeg",
                    "url": "tipsymix.com/api/cocktails/raspberry-collins",
                    "color": 0xBC1301
                }
            ]
        }
        
## Get All Cocktails [/api/search?category=cocktails]

### Query [GET]

+ Response 200 (application/json)

        {
            "category": "cocktails",
            "query": "",
            "filter": "",
            "totalCount": 90,
            "totalPages": 30,
            "count": 3
            "page": 2
            "results": [
                {
                    "id": 2349542,
                    "stdname": "raspberry-margarita",
                    "label": "Raspberry Margarita",
                    "image": "internal/2349542.jpeg",
                    "url": "tipsymix.com/api/cocktails/raspberry-margarita",
                    "color": 0xA81503
                }, {
                    "id": 2349299,
                    "stdname": "raspberry-mojito",
                    "label": "Raspberry Mojito",
                    "image": "internal/2349299.jpeg",
                    "url": "tipsymix.com/api/cocktails/raspberry-mojito",
                    "color": 0xDA3A13
                }, {
                    "id": 5693234,
                    "stdname": "raspberry-collins",
                    "label": "Raspberry Collins",
                    "image": "internal/5693234.jpeg",
                    "url": "tipsymix.com/api/cocktails/raspberry-collins",
                    "color": 0xBC1301
                }
            ]
        }

## Get All Ingredients [/api/search?category=ingredients]

### Query [GET]

+ Response 200 (application/json)

        {
            "category": "ingredients",
            "query": "",
            "filter": "",
            "totalCount": 90,
            "totalPages": 30,
            "count": 3
            "page": 2
            "results": [
                {
                    "id": 2349542,
                    "stdname": "raspberry-margarita",
                    "label": "Raspberry Margarita",
                    "image": "internal/2349542.jpeg",
                    "url": "tipsymix.com/api/cocktails/raspberry-margarita",
                    "color": 0xA81503
                }, {
                    "id": 2349299,
                    "stdname": "raspberry-mojito",
                    "label": "Raspberry Mojito",
                    "image": "internal/2349299.jpeg",
                    "url": "tipsymix.com/api/cocktails/raspberry-mojito",
                    "color": 0xDA3A13
                }, {
                    "id": 5693234,
                    "stdname": "raspberry-collins",
                    "label": "Raspberry Collins",
                    "image": "internal/5693234.jpeg",
                    "url": "tipsymix.com/api/cocktails/raspberry-collins",
                    "color": 0xBC1301
                }
            ]
        }

## Get All Brands [/api/search?category=brands]

### Query [GET]

+ Response 200 (application/json)

        {
            "category": "brands",
            "query": "",
            "filter": "",
            "totalCount": 90,
            "totalPages": 30,
            "count": 3
            "page": 2
            "results": [
                {
                    "id": 2349542,
                    "stdname": "raspberry-margarita",
                    "label": "Raspberry Margarita",
                    "image": "internal/2349542.jpeg",
                    "url": "tipsymix.com/api/cocktails/raspberry-margarita",
                    "color": 0xA81503
                }, {
                    "id": 2349299,
                    "stdname": "raspberry-mojito",
                    "label": "Raspberry Mojito",
                    "image": "internal/2349299.jpeg",
                    "url": "tipsymix.com/api/cocktails/raspberry-mojito",
                    "color": 0xDA3A13
                }, {
                    "id": 5693234,
                    "stdname": "raspberry-collins",
                    "label": "Raspberry Collins",
                    "image": "internal/5693234.jpeg",
                    "url": "tipsymix.com/api/cocktails/raspberry-collins",
                    "color": 0xBC1301
                }
            ]
        }

## Get All Countries [/api/search?category=countries]

### Query [GET]

+ Response 200 (application/json)

        {
            "category": "countries",
            "query": "",
            "filter": "",
            "totalCount": 90,
            "totalPages": 30,
            "count": 3
            "page": 2
            "results": [
                {
                    "id": 2349542,
                    "stdname": "raspberry-margarita",
                    "label": "Raspberry Margarita",
                    "image": "internal/2349542.jpeg",
                    "url": "tipsymix.com/api/cocktails/raspberry-margarita",
                    "color": 0xA81503
                }, {
                    "id": 2349299,
                    "stdname": "raspberry-mojito",
                    "label": "Raspberry Mojito",
                    "image": "internal/2349299.jpeg",
                    "url": "tipsymix.com/api/cocktails/raspberry-mojito",
                    "color": 0xDA3A13
                }, {
                    "id": 5693234,
                    "stdname": "raspberry-collins",
                    "label": "Raspberry Collins",
                    "image": "internal/5693234.jpeg",
                    "url": "tipsymix.com/api/cocktails/raspberry-collins",
                    "color": 0xBC1301
                }
            ]
        }

## Cocktail Detail [/api/cocktails/{slug}]

+ Parameters
    + slug - identifier for detail page, either an ID number or standardized name

### Cocktail Data [GET]

+ Response 200 (application/json)

        {
            "id": 5693234,
            "stdname": "raspberry-collins",
            "name": "Raspberry Collins",
            "image": "internal/5693234.jpeg",
            "color": 0xBC1301,
            "description": "Find out what happens when you add raspberries to this classic gin drink."
            "abv": 0.15,
            "video": "https://www.youtube.com/watch?v=CPIpicaoe"
            "ingredients": [
                {
                    "ingredient": "Gin",
                    "quantity": "2 oz",
                    "id": 843923,
                    "url": "tipsymix.com/api/ingredients/gin"
                }, {
                    "ingredient": "Simple syrup",
                    "quantity": "1/4 oz",
                    "id": 134932,
                    "url": "tipsymix.com/api/ingredients/simple-syrup"
                }, {
                    "ingredient": "Raspberries",
                    "quantity": "2",
                    "id": ,
                    "url":
                }, {
                    "ingredient": "Fresh lemon juice",
                    "quantity": "1 oz",
                    "id": 4328532,
                    "url": "tipsymix.com/api/ingredients/lemon-juice"
                }, {
                    "ingredient": "Club soda",
                    "quantity": "1 oz",
                    "id": 2345,
                    "url": "tipsymix.com/api/ingredients/club-soda"
                }
            ],
            "garnish": "1 lemon wheel, mint sprig, and raspberries",
            "glass": "Highball",
            "base spirit": "Gin",
            "preparation": "Stirred",
            "tags": [
                "Summer",
                "Fruity",
                "Citrus",
                "Sweet",
                "Dinner",
                "Evening",
                "Modern Classics"
            ],
            "brands": [
                {
                    "brand": "Beefeater",
                    "id": 82944,
                    "url": "tipsymix.com/api/brands/beefeater"
                }
            ],
            "instructions": "In a highball glass, muddle the raspberries and simple syrup...",
            "countries": [
                {
                    "label": "USA",
                    "id": 1341,
                    "url": "tipsymix.com/api/countries/usa"
                }
            ]
        }

## Ingredient Detail [/api/ingredients/{slug}]

+ Parameters
    + slug - identifier for detail page, either an ID number or standardized name

### Ingredient Data [GET]

+ Response 200 (application/json)

        {
            "id": 4625843,
            "stdname": "campari",
            "name": "Campari",
            "image": "internal/4625843.jpeg",
            "color": 0xA81510,
            "description": "Campari is an alcoholic liqueur, considered an apéritif, obtained from the infusion of herbs and fruit...",
            "abv": 0.21
            "brands": [
                {
                    "label": "Campari",
                    "id": 74244
                    "url": "tipsymix.com/api/brands/campari"
                }
            ],
            "cocktails": [
                {
                    "label": "Campari Orange",
                    "id": 894352
                    "url": "tipsymix.com/api/cocktails/campari-orange"
                }, {
                    "label": "Americano",
                    "id": 995123
                    "url": "tipsymix.com/api/cocktails/americano"
                }, {
                    "label": "Negroni",
                    "id": 2848
                    "url": "tipsymix.com/api/cocktails/negroni"
                }
            ],
            "tags": [
                "Bitter",
                "Herbal",
                "Aperitif",
                "Evening"
            ],
            "countries": [
                {
                    "label": "Italy",
                    "id": 2342
                    "url": "tipsymix.com/api/counries/italy"
                }
            ]
        }

## Brand Detail [/api/brands/{slug}]

+ Parameters
    + slug - identifier for detail page, either an ID number or standardized name

### Brand Data [GET]

+ Response 200 (application/json)

        {
            "id": 842321,
            "stdname": "jagermeister",
            "name": "Mast-Jägermeister",
            "image": "internal/842321.jpeg",
            "color": 0x161E29,
            "description": "Mast-Jägermeister SE is a German liquor company owned by the Findel-Mast family.",
            "ingredients": [
                {
                    "label": "Jägermeister",
                    "id": 98743
                    "url": "tipsymix.com/api/ingredients/jagermeister"
                }
            ],
            "cocktails": [
                {
                    "label": "Jäger Bomb",
                    "id": 67684
                    "url": "tipsymix.com/api/cocktails/jagerbomb"
                }, {
                    "label": "Monster Bomb",
                    "id": 998732
                    "url": "tipsymix.com/api/cocktails/monsterbomb"
                }
            ],
            "tags": [
                "one-hit wonder"
            ],
            "website": "www.jaegermeister.de",
            "countries": [
                {
                    "label": "Germany",
                    "id": 1687
                    "url": "tipsymix.com/api/counries/germany"
                }
            ]
        }

## Country Detail [/api/countries/{slug}]

+ Parameters
    + slug - identifier for detail page, either an ID number or standardized name

### Country Data [GET]

+ Response 200 (application/json)

        {
            "id": 9735,
            "stdname": "germany",
            "name": "Germany",
            "image": "internal/9735.jpeg",
            "color": 0x132414,
            "description": "Germany is a federal parliamentary republic in central-western Europe",
            "continent": "Europe",
            "ingredients": [
                {
                    "label": "Jägermeister",
                    "id": 98743
                    "url": "tipsymix.com/api/ingredients/jagermeister"
                }, {
                    "label": "Korn",
                    "id": 1354884
                    "url": "tipsymix.com/api/ingredients/korn
                }, {
                    "label": "Egg liquor",
                    "id": 498732
                    "url": "tipsymix.com/api/ingredients/egg-liquor"
                }, {
                    "label": "Brandy",
                    "id": 76543
                    "url": "tipsymix.com/api/ingredients/brandy"
                }
            ],
            "cocktails": [
                {
                    "label": "Black Magic",
                    "id": 67684
                    "url": "tipsymix.com/api/cocktails/black-magic"
                }, {
                    "label": "Goldfinger",
                    "id": 468432
                    "url": "tipsymix.com/api/cocktails/goldfinger"
                }, {
                    "label": "Golden Sunset",
                    "id": 765423
                    "url": "tipsymix.com/api/ingredients/golden-sunset"
                }, {
                    "label": "Kirsch & Coffee",
                    "id": 159976
                    "url": "tipsymix.com/api/ingredients/kirsh-coffee"
                }
            ],
            "brands": [
                {
                    "label": "Verpoorten",
                    "id": 1687
                    "url": "tipsymix.com/api/brands/verpoorten"
                }, {
                    "label": "Mast-Jägermeister",
                    "id": 842321
                    "url": "tipsymix.com/api/brands/jagermeister"
                }, {
                    "label": "Asbach",
                    "id": 983434
                    "url": "tipsymix.com/api/brands/asbach"
                }
            ],
            "tags": [
                "WWII"
            ]
        }