#!/usr/bin/env python
from __future__ import with_statement, print_function
import os
import re
import shutil
import subprocess
import sys
import tempfile

try:
    import autopep8 as ap8
    import jsbeautifier as jsB
except ImportError:
    print("'autopep8' and 'js-beautify' is required. Please install with `pip install autopep8` and `pip install jsbeautifier`.", file=sys.stderr)
    exit(1)

# don't fill in both of these
select_codes = []
ignore_codes = ["E114", "E115", "E116", "E121", "E122", "E123", "E124", "E125", "E126", "E127", "E128", "E129", "E131", "E501", "E261", "E262", "E265", "E266", "E402", "E711", "E731", "E721"]
# Add things like "--max-line-length=120" below
overrides = ["--max-line-length=120"]


def system(*args, **kwargs):
    kwargs.setdefault('stdout', subprocess.PIPE)
    proc = subprocess.Popen(args, **kwargs)
    out, err = proc.communicate()
    return out


def autopep8(filepath):
    args = ['autopep8', '--in-place']
    if select_codes and ignore_codes:
        print(u'Error: select and ignore codes are mutually exclusive')
        sys.exit(1)
    elif select_codes:
        args.extend(('--select', ','.join(select_codes)))
    elif ignore_codes:
        args.extend(('--ignore', ','.join(ignore_codes)))
    args.extend(overrides)
    args.append(filepath)
    output = system(*args)

def jsBeauty(filepath):
    opts = jsB.default_options()
    opts.replace = True
    jsB.beautify_file(filepath, opts)


def main():
    modified = re.compile('^[AM]+\s+(?P<name>.*\.py)', re.MULTILINE)
    basedir = system('git', 'rev-parse', '--show-toplevel').decode("utf-8").strip()
    files = system('git', 'status', '--porcelain').decode("utf-8")
    files = modified.findall(files)

    for name in files:
        filepath = os.path.join(basedir, name)
        autopep8(filepath)
        system("git", "add", filepath)

    modified = re.compile('^[AM]+\s+(?P<name>.*\.js$)', re.MULTILINE)
    files = system('git', 'status', '--porcelain').decode("utf-8")
    files = modified.findall(files)

    for name in files:
        filepath = os.path.join(basedir, name)
        jsBeauty(filepath)
        system("git", "add", filepath)

if __name__ == '__main__':
    main()
