runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /frontend
  static_dir: /frontend
- url: /.*git
  script: main.app
# [END handlers]

libraries:
- name: MySQLdb
  version: "latest"

env_variables:
    CLOUDSQL_CONNECTION_NAME: tipsymix-ttp:us-central1:tipsy-db
    CLOUDSQL_USER: root
    CLOUDSQL_PASSWORD: tipsymix

beta_settings:
  cloud_sql_instances: "tipsymix-ttp:us-central1:tipsy-db"

skip_files:
- logs/
- env/
- .git
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- node_modules/
