runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /frontend
  static_dir: /frontend
- url: /.*
  script: main.app
# [END handlers]

beta_settings:
  cloud_sql_instances: "tipsymix-ttp:us-central1:tipsy-db"